version: '3'
services:
  dbservices:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root

    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306

  appservice:
    build: .././spring-boot-library
    depends_on:
      - dbservices

    environment:
      - spring.datasource.url=jdbc:mysql://dbservices:3306/reactlibrarydatabase?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - 8085:9292